import { useMemo, useState } from "react";
import { Badge, Drawer, Modal, Meter, Steps, useToast } from "../../../components/ui";

const providers = [
 ["KPLC (Prepaid)","Electricity","Meter #","Instant","1.0%","Active"],["KPLC (Postpaid)","Electricity","Account #","24–48h","1.0%","Active"],["Nairobi Water","Water","Account #","24h","1.0%","Active"],["Safaricom Airtime","Telecom","Phone #","Instant","0%","Active"],["Airtel Airtime","Telecom","Phone #","Instant","0%","Active"],["DStv / GoTV","TV","Smartcard #","Instant","1.0%","Active"],["Zuku / FAIBA","Internet","Account #","2h","1.0%","Active"],["Kenya Power Tokens","Electricity","Meter #","Instant","1.0%","Active"],["NHIF","Insurance","ID #","24h","1.0%","Active"],["NSSF","Social Security","ID #","24h","1.0%","Active"],["KRA Tax","Government","PIN","Instant","1.0%","Active"],["County Governments","Government","Account #","24h","1.0%","Active"]
];
const volume = [["KPLC Prepaid","45,600","KES 89.2M","KES 1,956","KES 892K","+12%"],["Safaricom Airtime","34,200","KES 34.2M","KES 1,000","KES 0","+5%"],["DStv / GoTV","12,300","KES 36.9M","KES 3,000","KES 369K","+8%"],["Nairobi Water","8,900","KES 26.7M","KES 3,000","KES 267K","+3%"],["NHIF","6,700","KES 33.5M","KES 5,000","KES 335K","+15%"],["KRA Tax","5,400","KES 234.5M","KES 43,426","KES 2.3M","+22%"],["Others","21,800","KES 67.8M","KES 3,110","KES 678K","+7%"]];
const failures = [["KPLC Prepaid","234","Invalid meter #","95%","1 hour"],["KPLC Postpaid","123","Amount mismatch","90%","24 hours"],["DStv","89","Invalid smartcard","92%","2 hours"],["Nairobi Water","67","Account not found","88%","4 hours"],["KRA","45","PIN validation failure","85%","24 hours"]];
const health = [["KPLC","99.95%","3.2s","0.15%","99.90%","Healthy"],["Safaricom Airtime","99.99%","1.1s","0.02%","99.95%","Healthy"],["DStv","99.90%","5.4s","0.25%","99.90%","Healthy"],["Nairobi Water","99.85%","8.2s","0.35%","99.80%","Watch"],["KRA","99.92%","4.5s","0.18%","99.90%","Healthy"]];
const pipeline = [["Kenya Airways","Travel","Integration","Oct 2026","Partnerships", "60%"],["HELB","Education","Contract","Nov 2026","Partnerships", "20%"],["Teacher Service Commission","Government","Negotiation","Dec 2026","Partnerships", "10%"],["NHIF Upgrade","Insurance","Testing","Sep 2026","Tech", "80%"]];
const shares = [["KPLC","1.0%","99.0%","Daily","Active"],["DStv","1.0% + KES 50","99.0% − KES 50","Weekly","Active"],["Nairobi Water","1.5%","98.5%","Weekly","Active"],["KRA","1.0%","99.0%","Daily","Active"],["Airtime","0%","100% (telco absorbs)","Real-time","Active"]];

type Action = { title:string; body:React.ReactNode; tone?:"green"|"red"|"amber"|"blue"|"violet"|"ink"; icon?:string };
export function UtilityServices({ signal: _signal }: { signal:{action:string;n:number}; onNavigate:(id:string)=>void }) {
 const {push}=useToast(); const [tab,setTab]=useState("providers"); const [query,setQuery]=useState(""); const [action,setAction]=useState<Action|null>(null); const [drawer,setDrawer]=useState<string|null>(null); const [wizard,setWizard]=useState(false); const [step,setStep]=useState(0);
 const filtered=useMemo(()=>providers.filter(r=>r.join(" ").toLowerCase().includes(query.toLowerCase())),[query]);
 const ask=(title:string,body:React.ReactNode,tone:Action["tone"]="green",icon="bi-check2-circle")=>setAction({title,body,tone,icon});
 const submit=()=>{setWizard(false);push({kind:"success",title:"Provider submitted for review",body:"Integration checklist UTY-024 was created with dual-control approval."});};
 return <div className="pm-page-content utility-page">
  <div className="pm-section-head" style={{marginTop:0}}><div><div className="pm-eyebrow">PRODUCTS & SERVICES / PAGE 24</div><h2 className="mb-1">Utility Services</h2><p>Manage bill payment integrations, utility providers, commissions and auto-pay operations.</p></div><div className="d-flex gap-2 flex-wrap"><button className="btn btn-outline-secondary btn-sm" onClick={()=>setDrawer("audit")}><i className="bi bi-clock-history me-1"/>Audit trail</button><button className="btn btn-outline-primary btn-sm" onClick={()=>setDrawer("autopay")}><i className="bi bi-arrow-repeat me-1"/>Auto-pay controls</button><button className="btn btn-primary btn-sm" onClick={()=>{setStep(0);setWizard(true)}}><i className="bi bi-plus-lg me-1"/>Onboard provider</button></div></div>
  <div className="pm-hero utility-hero mb-3"><div className="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><div className="pm-eyebrow text-white-50">UTILITY PAYMENTS · LIVE</div><div className="pm-hero-value">KES 522.8M <span className="fs-6 fw-normal text-white-50">processed in 30d</span></div><div className="small text-white-50 mt-2">134,900 payments · 234 providers in the registry · 99.94% uptime</div></div><div className="d-flex gap-2 flex-wrap"><div className="pm-hero-chip"><div className="l">Commission revenue</div><div className="v">KES 4.8M</div></div><div className="pm-hero-chip"><div className="l">Auto-pay active</div><div className="v">28,900</div></div><div className="pm-hero-chip"><div className="l">Failed payments</div><div className="v text-warning">1,234</div></div></div></div></div>
  <div className="row g-3 mb-3">{[["Providers", "234", "12 core integrations", "bi-building", "green"],["Payments (30d)","134,900","+11% month on month","bi-receipt","blue"],["Auto-pay setups","34,500","83.8% active","bi-arrow-repeat","violet"],["Integration health","99.94%","4 providers above SLA","bi-heart-pulse","amber"]].map(x=><div className="col-6 col-xl-3" key={x[0]}><div className="pm-stat"><div className={`pm-stat-ico bg-${x[4]}-soft text-${x[4]}`}><i className={`bi ${x[3]}`}/></div><div className="pm-stat-label">{x[0]}</div><div className="pm-stat-value">{x[1]}</div><div className="pm-stat-foot">{x[2]}</div></div></div>)}</div>
  <div className="pm-card mb-3"><div className="pm-tabs">{[["providers","Provider directory","bi-buildings"],["volume","Payment volume","bi-bar-chart-line"],["autopay","Auto-pay","bi-arrow-repeat"],["failures","Failed payments","bi-exclamation-triangle"],["health","Integration health","bi-heart-pulse"],["pipeline","Onboarding pipeline","bi-kanban"],["analytics","Analytics","bi-graph-up-arrow"],["shares","Revenue sharing","bi-percent"]].map(x=><button key={x[0]} className={`pm-tab ${tab===x[0]?"active":""}`} onClick={()=>setTab(x[0])}><i className={`bi ${x[2]}`}/>{x[1]}</button>)}</div></div>
  {tab==="providers"&&<section><div className="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3"><div><h3>Provider directory</h3><p>Active billers, account validation rules and confirmation windows.</p></div><div className="pm-search"><i className="bi bi-search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search provider or category"/></div></div><div className="pm-card"><Table headers={["Provider","Category","Account format","Confirmation","Fee","Status","Actions"]} rows={filtered} render={r=><>{r.map((x,i)=><td key={i} className={i===0?"pm-td-strong":""}>{i===5?<Badge tone="green" dot>{x}</Badge>:x}</td>)}<td><button className="btn btn-sm btn-outline-secondary" onClick={()=>setDrawer(r[0])}>Manage</button></td></>}/><div className="pm-table-foot"><span>Showing {filtered.length} of 234 providers</span><button className="btn btn-link btn-sm" onClick={()=>ask("Registry export ready","The provider registry export has been prepared as a CSV manifest.","blue","bi-download")}>Export registry</button></div></div></section>}
  {tab==="volume"&&<section><SectionHead title="Payment volume & commission" body="Provider-level performance for the last 30 days." action={()=>ask("Volume report generated","The 30-day utility volume report is ready for download.","blue","bi-file-earmark-bar-graph")}/><div className="pm-card"><Table headers={["Provider","Payments","Volume","Avg amount","Commission","Growth"]} rows={volume} render={r=><>{r.map((x,i)=><td key={i} className={i>0?"pm-num":"pm-td-strong"}>{i===5?<Badge tone="green">{x}</Badge>:x}</td>)}</>}/></div><div className="row g-3 mt-1"><div className="col-md-6"><Insight title="Peak payment window" value="08:00–10:00" body="31% of daily utility volume · Nairobi and Kiambu lead" icon="bi-clock"/></div><div className="col-md-6"><Insight title="Fastest growing biller" value="KRA Tax · +22%" body="KES 234.5M processed in the last 30 days" icon="bi-graph-up-arrow"/></div></div></section>}
  {tab==="autopay"&&<section><SectionHead title="Auto-pay management" body="Standing utility mandates and scheduled bill payment health." action={()=>setDrawer("autopay")}/><div className="row g-3 mb-3">{[["Total setups","34,500","Across 18 billers"],["Active (30d)","28,900","83.8% activation"],["Failures (30d)","1,234","4.3% failure rate"],["Auto-pay revenue","KES 8.7M","30-day volume"]].map(x=><div className="col-6 col-xl-3" key={x[0]}><div className="pm-stat"><div className="pm-stat-label">{x[0]}</div><div className="pm-stat-value">{x[1]}</div><div className="pm-stat-foot">{x[2]}</div></div></div>)}</div><div className="pm-card pm-card-pad"><div className="d-flex justify-content-between"><div><h5 className="pm-card-title">Top auto-pay providers</h5><p className="pm-card-sub">KPLC Prepaid leads with 12,400 active setups.</p></div><button className="btn btn-outline-primary btn-sm" onClick={()=>ask("Create auto-pay campaign",<SettingsForm title="Auto-pay campaign"/> ,"violet","bi-megaphone")}>Create campaign</button></div><div className="mt-3"><div className="d-flex justify-content-between small mb-1"><span>KPLC Prepaid</span><b>12,400</b></div><Meter value={100} width={"100%" as unknown as number}/><div className="d-flex justify-content-between small mb-1 mt-3"><span>Nairobi Water</span><b>6,840</b></div><Meter value={55} width={"100%" as unknown as number}/><div className="d-flex justify-content-between small mb-1 mt-3"><span>DStv / GoTV</span><b>4,920</b></div><Meter value={40} width={"100%" as unknown as number}/></div></div></section>}
  {tab==="failures"&&<section><SectionHead title="Failed utility payments" body="Refund posture, root causes and operations resolution time." action={()=>ask("Retry policy updated",<SettingsForm title="Retry and refund policy"/>,"amber","bi-arrow-repeat")}/><div className="pm-card"><Table headers={["Provider","Failures (30d)","Primary reason","Auto-refund","Avg resolution","Actions"]} rows={failures} render={r=><>{r.map((x,i)=><td key={i} className={i===1?"pm-num":i===0?"pm-td-strong":""}>{i===3?<Badge tone={Number.parseInt(x)>=90?"green":"amber"}>{x}</Badge>:x}</td>)}<td><button className="btn btn-sm btn-outline-primary" onClick={()=>setDrawer(r[0])}>Review</button></td></>}/></div></section>}
  {tab==="health"&&<section><SectionHead title="Provider integration health" body="Availability, latency and SLA compliance across critical billers." action={()=>setDrawer("health")}/><div className="pm-card"><Table headers={["Provider","Uptime (30d)","Avg latency","Error rate","SLA","Status"]} rows={health} render={r=><>{r.map((x,i)=><td key={i} className={i>0&&i<5?"pm-num":i===0?"pm-td-strong":""}>{i===5?<Badge tone={x==="Watch"?"amber":"green"} dot>{x}</Badge>:x}</td>)}</>}/></div><div className="pm-card pm-card-pad mt-3 border-warning"><div className="d-flex gap-2"><i className="bi bi-exclamation-triangle-fill text-warning"/><div><b>Nairobi Water is approaching its SLA threshold</b><div className="pm-td-sub">8.2s average latency · 0.35% error rate · open incident UTY-118 assigned to Integrations.</div></div><button className="btn btn-sm btn-outline-secondary ms-auto" onClick={()=>ask("Incident UTY-118","The incident has been opened in the integration operations queue.","amber","bi-fire")}>Open incident</button></div></div></section>}
  {tab==="pipeline"&&<section><SectionHead title="Provider onboarding pipeline" body="Integration, commercial and compliance readiness for new billers." action={()=>setWizard(true)}/><div className="pm-card"><Table headers={["Provider","Category","Stage","Target go-live","Owner","Progress","Action"]} rows={pipeline} render={r=><>{r.map((x,i)=><td key={i} className={i===0?"pm-td-strong":i===5?"pm-num":""}>{i===5?<><b>{x}</b><Meter value={Number.parseInt(x)}/></>:x}</td>)}<td><button className="btn btn-sm btn-outline-primary" onClick={()=>setDrawer(r[0])}>Open</button></td></>}/></div></section>}
  {tab==="analytics"&&<section><SectionHead title="Utility payment analytics" body="Operational patterns to inform staffing, liquidity and provider capacity." action={()=>ask("Analytics export ready","County, segment and hour-of-day analytics have been packaged.","blue","bi-download")}/><div className="row g-3"><div className="col-lg-8"><div className="pm-card pm-card-pad"><h5 className="pm-card-title">Payment volume by hour</h5><div className="bar-chart mt-3">{[18,24,34,42,58,82,100,92,76,64,52,48,55,67,72,68,61,54,47,38,30,25,20,16].map((h,i)=><div className="bar" style={{height:`${h}%`}} key={i}><span>{i}</span></div>)}</div><div className="pm-td-sub mt-2">Peak demand is 08:00–10:00; schedule reconciliation and support coverage accordingly.</div></div></div><div className="col-lg-4"><div className="pm-card pm-card-pad h-100"><h5 className="pm-card-title">Leading segments</h5>{[["Mass market","46%","#12b76a"],["SME","28%","#2e90fa"],["Enterprise","16%","#7a5af8"],["Government","10%","#f79009"]].map(x=><div key={x[0]} className="mt-3"><div className="d-flex justify-content-between small"><span>{x[0]}</span><b>{x[1]}</b></div><Meter value={Number.parseInt(x[1])} tone={x[2]} width={"100%" as unknown as number}/></div>)}</div></div></div></section>}
  {tab==="shares"&&<section><SectionHead title="Utility revenue sharing" body="Commission terms, settlement cadence and partner share." action={()=>ask("Settlement terms exported","The current commission grid was exported for Finance.","blue","bi-download")}/><div className="pm-card"><Table headers={["Provider","PayMo commission","Provider share","Settlement","Status","Action"]} rows={shares} render={r=><>{r.map((x,i)=><td key={i} className={i===0?"pm-td-strong":""}>{i===4?<Badge tone="green" dot>{x}</Badge>:x}</td>)}<td><button className="btn btn-sm btn-outline-secondary" onClick={()=>ask(`Edit ${r[0]} terms`,<SettingsForm title="Commission terms"/>,"violet","bi-percent")}>Edit</button></td></>}/></div></section>}
  <Modal open={!!action} onClose={()=>setAction(null)} title={action?.title??"Utility action"} subtitle="Super Admin action · all changes are logged" icon={action?.icon} tone={action?.tone} size="md"><div className="pm-modal-body">{action?.body}</div><div className="pm-modal-foot"><button className="btn btn-outline-secondary" onClick={()=>setAction(null)}>Cancel</button><button className="btn btn-primary" onClick={()=>{setAction(null);push({kind:"success",title:"Action completed",body:"Utility operations have been updated."})}}>Confirm action</button></div></Modal>
  <Modal open={wizard} onClose={()=>setWizard(false)} title="Onboard utility provider" subtitle="Validate commercial, technical and operational readiness" icon="bi-building-add" tone="green" size="lg"><Steps current={step} steps={[{label:"Provider",icon:"bi-building"},{label:"Integration",icon:"bi-plug"},{label:"Commercial",icon:"bi-percent"},{label:"Review",icon:"bi-check2"}]}/><div className="pm-wizard-progress"><span style={{width:`${(step+1)*25}%`}}/></div><div className="pm-modal-body">{step===0?<SettingsForm title="Provider identity"/>:step===1?<SettingsForm title="Integration endpoint"/>:step===2?<SettingsForm title="Commission and settlement"/>:<div className="pm-card pm-card-pad"><Badge tone="green" dot>Ready for approval</Badge><h6 className="mt-3">New utility provider</h6><p className="small text-muted">Sandbox credentials, callback signing and refund policy will be validated before go-live.</p><ul className="small text-muted"><li>Account validation enabled</li><li>24-hour reconciliation window</li><li>Dual approval required</li></ul></div>}</div><div className="pm-modal-foot"><button className="btn btn-outline-secondary" onClick={()=>step?setStep(step-1):setWizard(false)}>{step?"Back":"Cancel"}</button>{step<3?<button className="btn btn-primary" onClick={()=>setStep(step+1)}>Continue <i className="bi bi-arrow-right ms-1"/></button>:<button className="btn btn-primary" onClick={submit}>Submit for approval</button>}</div></Modal>
  <Drawer open={!!drawer} onClose={()=>setDrawer(null)} title={drawer??"Utility operations"} subtitle="Provider operations, configuration and event history" icon="bi-lightning-charge" wide><div className="pm-card pm-card-pad mb-3"><div className="d-flex justify-content-between"><div><h5>{drawer}</h5><Badge tone="green" dot>Operational</Badge></div><button className="btn btn-sm btn-outline-primary" onClick={()=>ask("Provider configuration",<SettingsForm title={drawer??"Provider"}/>,"blue","bi-sliders")}>Edit settings</button></div><div className="row g-3 mt-2"><div className="col-4"><div className="pm-eyebrow">Uptime</div><b>99.95%</b></div><div className="col-4"><div className="pm-eyebrow">Latency</div><b>3.2s</b></div><div className="col-4"><div className="pm-eyebrow">Settlement</div><b>Daily</b></div></div></div><div className="pm-card pm-card-pad mb-3"><h6>Quick operations</h6><div className="d-grid gap-2"><button className="btn btn-outline-primary" onClick={()=>ask("Test provider connection", "A signed health check was sent to the provider sandbox. Response received in 1.8 seconds.","green","bi-broadcast")}>Run connection test</button><button className="btn btn-outline-secondary" onClick={()=>ask("Reconciliation started","The latest provider file was queued for matching.","blue","bi-arrow-left-right")}>Run reconciliation</button><button className="btn btn-outline-danger" onClick={()=>ask("Pause provider payments?","New payments will be held while existing refunds and callbacks continue.","red","bi-pause-circle")}>Pause new payments</button></div></div><div className="pm-card pm-card-pad"><h6>Recent events</h6><div className="pm-timeline"><div className="pm-tl-item done"><b>Health check passed</b><div className="pm-td-sub">Aug 23 · 14:22 · 1.8s response</div></div><div className="pm-tl-item done"><b>Settlement file reconciled</b><div className="pm-td-sub">Aug 23 · 12:00 · 4,820 payments</div></div><div className="pm-tl-item warn"><b>Refund threshold reviewed</b><div className="pm-td-sub">Aug 22 · Finance operations</div></div></div></div></Drawer>
 </div>;
}
function Table({headers,rows,render}:{headers:string[];rows:string[][];render:(r:string[],i:number)=>React.ReactNode}){return <div className="pm-table-wrap"><table className="pm-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r[0]}>{render(r,i)}</tr>)}</tbody></table></div>}
function SectionHead({title,body,action}:{title:string;body:string;action:()=>void}){return <div className="pm-section-head"><div><h3>{title}</h3><p>{body}</p></div><button className="btn btn-outline-secondary btn-sm" onClick={action}><i className="bi bi-download me-1"/>Export / manage</button></div>}
function SettingsForm({title}:{title:string}){return <div className="row g-3"><div className="col-md-7"><label className="form-label">{title}</label><input className="form-control" defaultValue="PayMo Utility Operations"/></div><div className="col-md-5"><label className="form-label">Status</label><select className="form-select"><option>Active</option><option>Sandbox</option><option>Paused</option></select></div><div className="col-md-6"><label className="form-label">Confirmation window</label><input className="form-control" defaultValue="Instant"/></div><div className="col-md-6"><label className="form-label">Refund window</label><input className="form-control" defaultValue="24 hours"/></div><div className="col-12"><label className="form-label">Operations note</label><textarea className="form-control" rows={3} defaultValue="Changes are versioned and require Finance plus Risk approval."/></div></div>}
function Insight({icon,title,value,body}:{icon:string;title:string;value:string;body:string}){return <div className="pm-card pm-card-pad"><div className="d-flex gap-2"><div className="pm-stat-ico bg-green-soft text-green"><i className={`bi ${icon}`}/></div><div><div className="pm-stat-label">{title}</div><div className="h5 mb-1">{value}</div><div className="pm-td-sub">{body}</div></div></div></div>}
