import { useMemo, useState } from "react";
import { Avatar, Badge, DDItem, Drawer, Dropdown, Meter, Modal, Steps, useToast } from "../../../components/ui";

const programs = [
  ["PayMo Debit", "Physical", "67,800", "54,200", "234", "KES 18.4M", "0.012%", "KES 450", "Visa"],
  ["PayMo Virtual", "Virtual", "34,500", "28,900", "123", "KES 6.2M", "0.008%", "KES 0", "Mastercard"],
  ["PayMo Corporate", "Corporate", "2,340", "1,890", "12", "KES 4.5M", "0.005%", "KES 600", "Visa"],
  ["PayMo Prepaid", "Prepaid", "12,400", "8,900", "45", "KES 1.8M", "0.015%", "KES 200", "Mastercard"],
  ["PayMo Premium Metal", "Metal", "450", "420", "0", "Bundled", "0%", "KES 2,500", "Visa"],
];
const issuance = [
  ["CRD-8821", "Wanjiku Mwangi", "PAY-12345", "Physical", "In production", "Aug 20", "2 days"],
  ["CRD-8820", "Otieno Ochieng", "PAY-67890", "Virtual", "Issued", "Aug 22", "Instant"],
  ["CRD-8819", "Aisha Hassan", "PAY-89012", "Corporate", "Pending approval", "Aug 21", "—"],
  ["CRD-8818", "Kamau Ndira", "PAY-11223", "Physical", "Shipped", "Aug 19", "3 days"],
  ["CRD-8817", "Fatuma Ali", "PAY-44556", "Prepaid", "Pending approval", "Aug 22", "—"],
  ["CRD-8816", "Brian Kiptoo", "PAY-15002", "Virtual", "Issued", "Aug 22", "Instant"],
  ["CRD-8815", "Mercy Wafula", "PAY-15003", "Physical", "In production", "Aug 21", "2 days"],
  ["CRD-8814", "Peter Mbugua", "PAY-15004", "Corporate", "Shipped", "Aug 18", "4 days"],
];
const fraud = [
  ["Card-not-present fraud", "8", "KES 234K", "Velocity + amount rules", "KES 180K", "77%"],
  ["Lost / stolen card", "5", "KES 89K", "User report", "KES 67K", "75%"],
  ["Counterfeit card", "2", "KES 45K", "EMV chip check", "KES 45K", "100%"],
  ["Card testing", "3", "KES 12K", "Velocity rules", "KES 12K", "100%"],
  ["Account takeover", "1", "KES 120K", "Behavioral analysis", "KES 80K", "67%"],
];
const controls = [
  ["Monthly spend limit", "KES 500K", "KES 200K", "KES 5M", "Loaded amount", "Unlimited"],
  ["Daily spend limit", "KES 100K", "KES 50K", "KES 1M", "Loaded amount", "Unlimited"],
  ["Per-transaction max", "KES 50K", "KES 30K", "KES 500K", "KES 50K", "Unlimited"],
  ["ATM daily", "KES 40K", "N/A", "KES 200K", "N/A", "Unlimited"],
  ["International", "Yes", "Yes", "Yes", "No", "Yes"],
  ["Online transactions", "Yes", "Yes", "Yes", "Yes", "Yes"],
  ["Contactless", "Yes", "No", "Yes", "No", "Yes"],
  ["Auto-lock on fraud", "Yes", "Yes", "Yes", "Yes", "Yes"],
];
const network = [["Visa", "78,200", "456,000", "KES 22.3M", "99.8%", "1.8s", "70 / 30"], ["Mastercard", "39,290", "234,000", "KES 8.6M", "99.7%", "1.9s", "70 / 30"]];
const config = [
  ["Default PIN try limit", "3", "Security", "Live"], ["PIN lock duration", "24 hours", "Security", "Live"], ["Auto-renew before expiry", "60 days", "Issuing", "Live"], ["Require activation for new cards", "Yes", "Issuing", "Live"], ["Activation method", "First TXN or app", "Issuing", "Live"], ["Allow temporary lock", "Yes", "Controls", "Live"], ["Real-time push on transaction", "Yes", "Notifications", "Live"], ["Push threshold", "> KES 1,000", "Notifications", "Live"],
];

type Action = { title: string; icon?: string; tone?: "green" | "red" | "amber" | "blue" | "violet" | "ink"; body: React.ReactNode };

export function CardPrograms({ signal }: { signal: { action: string; n: number }; onNavigate: (id: string) => void }) {
  const { push } = useToast();
  const [tab, setTab] = useState("overview");
  const [query, setQuery] = useState("");
  const [action, setAction] = useState<Action | null>(null);
  const [wizard, setWizard] = useState(false);
  const [wizardStep, setWizardStep] = useState(0);
  const [drawer, setDrawer] = useState<string | null>(null);
  const [enabled, setEnabled] = useState<Record<string, boolean>>({ activation: true, push: true, international: true, contactless: true });
  const [selected, setSelected] = useState<string[]>([]);
  const [notice, setNotice] = useState(0);
  const ask = (title: string, body: React.ReactNode, tone: Action["tone"] = "green", icon = "bi-check2-circle") => setAction({ title, body, tone, icon });
  const statusTone = (s: string) => s === "Issued" ? "green" : s === "Pending approval" ? "amber" : s === "Shipped" ? "blue" : "violet";
  const filteredIssuance = useMemo(() => issuance.filter(r => `${r[0]} ${r[1]} ${r[2]} ${r[3]} ${r[4]}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const toggleSelected = (id: string) => setSelected(x => x.includes(id) ? x.filter(i => i !== id) : [...x, id]);
  const openWizard = () => { setWizardStep(0); setWizard(true); };
  const bulkAction = () => ask("Bulk issuance review", <div><p>{selected.length} requests selected. Choose an operation:</p><div className="d-grid gap-2"><button className="btn btn-primary" onClick={() => { setSelected([]); setAction(null); push({kind:"success", title:"Requests approved", body:"The selected requests moved to production."}); }}>Approve selected</button><button className="btn btn-outline-secondary" onClick={() => setAction(null)}>Export manifest</button></div></div>);

  return <div className="pm-page-content card-programs-page">
    <div className="pm-section-head" style={{ marginTop: 0 }}>
      <div><div className="pm-eyebrow">PRODUCTS & SERVICES / PAGE 23</div><h2 className="mb-1">Card Programs</h2><p>Manage physical, virtual, corporate, prepaid and premium card products across Visa and Mastercard.</p></div>
      <div className="d-flex gap-2 flex-wrap"><button className="btn btn-outline-secondary btn-sm" onClick={() => setDrawer("audit")}><i className="bi bi-clock-history me-1" />Audit trail</button><button className="btn btn-outline-primary btn-sm" onClick={() => setWizard(true)}><i className="bi bi-plus-lg me-1" />New card program</button><button className="btn btn-primary btn-sm" onClick={() => { setTab("issuance"); setWizard(true); }}><i className="bi bi-credit-card-2-front me-1" />Issue card</button></div>
    </div>
    <div className="pm-hero card-hero mb-3"><div className="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><div className="pm-eyebrow text-white-50">CARD ESTATE · LIVE</div><div className="pm-hero-value">94,310 <span className="fs-6 fw-normal text-white-50">active cards</span></div><div className="small text-white-50 mt-2">117,490 issued across 5 programs · 80.3% activation rate</div></div><div className="d-flex gap-2 flex-wrap"><div className="pm-hero-chip"><div className="l">30d card revenue</div><div className="v">KES 30.9M</div></div><div className="pm-hero-chip"><div className="l">Fraud rate</div><div className="v text-success">0.010%</div></div><div className="pm-hero-chip"><div className="l">Cards blocked</div><div className="v text-warning">414</div></div></div></div></div>
    <div className="row g-3 mb-3">{[["Programs", "5", "All products live", "bi-collection", "green"], ["Cards issued", "117,490", "+4.8% vs last month", "bi-credit-card", "blue"], ["Pending issuance", "23", "8 need approval", "bi-hourglass-split", "amber"], ["Net margin", "62.7%", "KES 13.8M / 30d", "bi-graph-up-arrow", "violet"]].map(([l,v,f,i,t]) => <div className="col-6 col-xl-3" key={l}><div className="pm-stat"><div className={`pm-stat-ico bg-${t}-soft text-${t}`}><i className={`bi ${i}`} /></div><div className="pm-stat-label">{l}</div><div className="pm-stat-value">{v}</div><div className="pm-stat-foot">{f}</div></div></div>)}</div>
    <div className="pm-card mb-3"><div className="pm-tabs">{[["overview","Overview","bi-grid"],["issuance","Issuance queue","bi-inbox"],["controls","Limits & controls","bi-sliders"],["fraud","Fraud management","bi-shield-exclamation"],["network","Network performance","bi-diagram-3"],["pin","PIN & replacements","bi-key"],["financial","Financials","bi-bar-chart-line"],["config","Configuration","bi-gear" ]].map(([id,l,i]) => <button className={`pm-tab ${tab===id?"active":""}`} onClick={() => setTab(id)} key={id}><i className={`bi ${i}`} />{l}</button>)}</div></div>

    {tab === "overview" && <section><div className="pm-section-head"><div><h3>Program portfolio</h3><p>Performance and risk posture by card product. Click a row to inspect the program configuration.</p></div><button className="btn btn-outline-secondary btn-sm" onClick={() => setDrawer("programs")}><i className="bi bi-layout-sidebar-inset-reverse me-1" />Compare programs</button></div><div className="pm-card"><Table headers={["Program","Type","Issued","Active","Blocked","Revenue (30d)","Fraud rate","Cost / card","Network","Actions"]} rows={programs} onRow={(r) => setDrawer(r[0])} render={(r, i) => <><td><div className="d-flex align-items-center gap-2"><div className="pm-avatar sm" style={{ background: ["#12b76a","#2e90fa","#7a5af8","#f79009","#101828"][i] }}>{r[0][6]}</div><div><b>{r[0]}</b><div className="pm-td-sub">BIN 4278 {i + 1}xxx</div></div></div></td>{r.slice(1).map((x,j)=><td key={j} className={j > 1 ? "pm-num" : ""}>{x}</td>)}<td><Dropdown trigger={() => <button className="btn btn-sm btn-outline-secondary"><i className="bi bi-three-dots" /></button>}>{close => <><DDItem icon="bi-eye" label="View program" onClick={() => { close(); setDrawer(r[0]); }} /><DDItem icon="bi-pencil" label="Edit configuration" onClick={() => { close(); setAction({ title: "Edit program settings", icon: "bi-sliders", tone: "blue", body: <SettingsForm name={r[0]} /> }); }} /><DDItem icon="bi-pause-circle" label="Pause new issuance" onClick={() => { close(); ask("Issuance paused", <>New {r[0]} requests are paused. Existing cards remain active.</>, "amber", "bi-pause-circle"); }} /></>}</Dropdown></td></>}/></div></section>}
    {tab === "issuance" && <section><Toolbar query={query} setQuery={setQuery} selected={selected.length} onBulk={bulkAction} /><div className="pm-card"><Table headers={["Request","Customer","User ID","Type","Status","Requested","Processing","Actions"]} rows={filteredIssuance} render={(r) => <><td><input className="form-check-input me-2" type="checkbox" checked={selected.includes(r[0])} onChange={() => toggleSelected(r[0])}/><b className="mono">{r[0]}</b></td><td><div className="d-flex gap-2 align-items-center"><Avatar name={r[1]} size="sm" />{r[1]}</div></td><td className="mono">{r[2]}</td><td>{r[3]}</td><td><Badge tone={statusTone(r[4])} dot>{r[4]}</Badge></td><td>{r[5]}</td><td>{r[6]}</td><td><button className="btn btn-sm btn-outline-primary" onClick={() => setDrawer(r[0])}>{r[4] === "Pending approval" ? "Review" : "Track"}</button></td></>}/></div></section>}
    {tab === "controls" && <Controls onEdit={(name) => setAction({ title: `Edit ${name}`, subtitle: "Changes are versioned and require dual approval.", icon: "bi-shield-lock", tone: "amber", body: <SettingsForm name={name} /> })} />}
    {tab === "fraud" && <section><div className="row g-3 mb-3">{[["Fraud cases (30d)","19","-12%", "green"],["Gross exposure","KES 500K","5 cases open", "red"],["Recovered","KES 384K","76.8% recovery", "blue"]].map(x=><div className="col-md-4" key={x[0]}><div className="pm-card pm-card-pad"><div className="pm-stat-label">{x[0]}</div><div className="pm-stat-value">{x[1]}</div><span className={`pm-badge ${x[3]}`}>{x[2]}</span></div></div>)}</div><div className="pm-card"><Table headers={["Fraud type","Cases","Amount","Detection method","Recovery","Recovered"]} rows={fraud} render={r=><>{r.map((x,i)=><td key={i} className={i===2||i===4?"pm-num":""}>{i===5?<Badge tone={Number.parseInt(x)<80?"amber":"green"}>{x}</Badge>:x}</td>)}</>}/></div></section>}
    {tab === "network" && <section><div className="pm-card"><Table headers={["Network","Cards","TXN volume (30d)","TXN value (30d)","Success rate","Avg latency","Revenue share"]} rows={network} render={r=><>{r.map((x,i)=><td key={i} className={i>1?"pm-num":""}>{i===4?<><b>{x}</b><Meter value={Number.parseFloat(x)} /></>:x}</td>)}</>}/></div><div className="row g-3 mt-1"><div className="col-md-6"><Insight icon="bi-lightning-charge" title="Visa authorization health" value="99.8%" body="Within scheme SLA · 1.8s average latency" /></div><div className="col-md-6"><Insight icon="bi-arrow-repeat" title="Mastercard settlement" value="99.7%" body="Next file window in 42 minutes" /></div></div></section>}
    {tab === "pin" && <PinTab onAction={(t,b) => ask(t,b,"blue","bi-key")} />}
    {tab === "financial" && <Financials onAction={() => setDrawer("financials")} />}
    {tab === "config" && <Config enabled={enabled} setEnabled={setEnabled} onSave={() => { setNotice(n => n+1); push({kind:"success", title:"Configuration saved", body:"A versioned change was created for approval."}); }} />}

    {notice > 0 && <div className="pm-card mt-3 border-success"><div className="pm-card-pad d-flex gap-2 align-items-center"><i className="bi bi-check-circle-fill text-success" />Configuration draft v24 created · awaiting Risk and Product approval.<button className="btn btn-link btn-sm ms-auto" onClick={() => setNotice(0)}>Dismiss</button></div></div>}

    <Modal open={!!action} onClose={() => setAction(null)} title={action?.title ?? "Action"} subtitle="Super Admin action · all changes are logged" icon={action?.icon} tone={action?.tone} size="md"><div className="pm-modal-body">{action?.body}</div><div className="pm-modal-foot"><button className="btn btn-outline-secondary" onClick={() => setAction(null)}>Cancel</button><button className="btn btn-primary" onClick={() => { setAction(null); push({kind:"success", title:"Action completed", body:"The card program ledger has been updated."}); }}>Confirm action</button></div></Modal>
    <Modal open={wizard} onClose={() => setWizard(false)} title="Create card program" subtitle="Configure product, network and controls before submitting for approval" icon="bi-credit-card-2-front" tone="green" size="lg"><Steps current={wizardStep} steps={[{label:"Product",icon:"bi-box"},{label:"Network",icon:"bi-diagram-3"},{label:"Controls",icon:"bi-sliders"},{label:"Review",icon:"bi-check2"}]} /><div className="pm-wizard-progress"><span style={{width:`${(wizardStep+1)*25}%`}}/></div><div className="pm-modal-body">{wizardStep===0?<SettingsForm name="New program" />:wizardStep===1?<div className="row g-3"><div className="col-6"><button className="pm-opt active"><span className="r"/><i className="bi bi-credit-card-2-front fs-4 text-primary"/><span><b>Visa</b><small className="d-block text-muted">4278 BIN range · 70/30 share</small></span></button></div><div className="col-6"><button className="pm-opt"><span className="r"/><i className="bi bi-credit-card fs-4 text-danger"/><span><b>Mastercard</b><small className="d-block text-muted">5401 BIN range · 70/30 share</small></span></button></div></div>:wizardStep===2?<SettingsForm name="Program controls" />:<div className="pm-card pm-card-pad"><Badge tone="green" dot>Ready for approval</Badge><h6 className="mt-3">PayMo New Program</h6><p className="text-muted small">A configuration draft will be created. Risk and Product approvers must sign off before live issuance.</p><ul className="small text-muted"><li>Physical and virtual issuance enabled</li><li>Daily spend limit: KES 100,000</li><li>Fraud auto-lock enabled</li></ul></div>}</div><div className="pm-modal-foot"><button className="btn btn-outline-secondary" onClick={() => wizardStep ? setWizardStep(wizardStep-1) : setWizard(false)}>{wizardStep?"Back":"Cancel"}</button>{wizardStep<3?<button className="btn btn-primary" onClick={() => setWizardStep(wizardStep+1)}>Continue <i className="bi bi-arrow-right ms-1"/></button>:<button className="btn btn-primary" onClick={() => { setWizard(false); push({kind:"success",title:"Program submitted",body:"Approval request CRD-NEW-24 is now in the queue."}); }}>Submit for approval</button>}</div></Modal>
    <Drawer open={!!drawer && drawer !== "audit"} onClose={() => setDrawer(null)} title={drawer ?? "Card details"} subtitle="Card program operations and event history" icon="bi-credit-card-2-front" wide><div className="pm-card pm-card-pad mb-3"><div className="d-flex align-items-center gap-3"><div className="pm-avatar lg" style={{background:"#12b76a"}}>P</div><div><h5 className="mb-1">{drawer}</h5><Badge tone="green" dot>Operational</Badge></div></div><div className="row g-2 mt-3"><div className="col-4"><div className="pm-eyebrow">Issued</div><b>67,800</b></div><div className="col-4"><div className="pm-eyebrow">Active</div><b>54,200</b></div><div className="col-4"><div className="pm-eyebrow">Fraud rate</div><b>0.012%</b></div></div></div><div className="pm-card pm-card-pad mb-3"><h6>Quick operations</h6><div className="d-grid gap-2"><button className="btn btn-outline-primary" onClick={() => { setDrawer(null); openWizard(); }}><i className="bi bi-plus-lg me-1"/>Issue replacement</button><button className="btn btn-outline-secondary" onClick={() => ask("BIN range exported", "The encrypted BIN manifest is ready for download.", "blue", "bi-download")}><i className="bi bi-download me-1"/>Export BIN manifest</button><button className="btn btn-outline-danger" onClick={() => ask("Pause new issuance?", "Existing cards and authorisations remain unaffected. A dual-control approval will be required.", "red", "bi-pause-circle")}><i className="bi bi-pause-circle me-1"/>Pause issuance</button></div></div><div className="pm-card pm-card-pad"><h6>Recent events</h6><div className="pm-timeline"><div className="pm-tl-item done"><b>BIN range verified</b><div className="pm-td-sub">Aug 23 · Scheme operations</div></div><div className="pm-tl-item done"><b>Settlement file reconciled</b><div className="pm-td-sub">Aug 22 · 456,000 transactions</div></div><div className="pm-tl-item warn"><b>12 cards awaiting approval</b><div className="pm-td-sub">Aug 22 · Risk review queue</div></div></div></div></Drawer>
    <Drawer open={drawer === "audit"} onClose={() => setDrawer(null)} title="Card program audit trail" subtitle="Immutable admin activity across the card estate" icon="bi-clock-history" wide><div className="pm-card"><Table headers={["Time","Actor","Action","Object","Result"]} rows={[["Aug 23 · 14:32","Joseph Mwangi","Changed PIN try limit","Global config","Pending approval"],["Aug 23 · 12:08","V. Kiprop","Approved virtual BIN","PayMo Virtual","Applied"],["Aug 22 · 18:11","D. Kimani","Paused card CRD-8711","PAY-78901","Applied"],["Aug 22 · 10:45","System","Reconciled scheme file","Visa / 456K TXNs","Applied"]]} render={r=><>{r.map((x,i)=><td key={i} className={i===1?"pm-td-strong":""}>{x}</td>)}</>}/></div></Drawer>
  </div>;
}

function Table({ headers, rows, render, onRow }: { headers: string[]; rows: string[][]; render: (r: string[], i: number) => React.ReactNode; onRow?: (r: string[]) => void }) { return <div className="pm-table-wrap"><table className="pm-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r[0]} onClick={() => onRow?.(r)}>{render(r,i)}</tr>)}</tbody></table></div>; }
function Toolbar({ query, setQuery, selected, onBulk }: { query: string; setQuery:(x:string)=>void; selected:number; onBulk:()=>void }) { return <div className="d-flex gap-2 justify-content-between align-items-center flex-wrap mb-3"><div className="pm-search"><i className="bi bi-search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search request, customer or user ID"/><kbd className="pm-kbd">/</kbd></div><div className="d-flex gap-2"><button className="btn btn-outline-secondary btn-sm"><i className="bi bi-funnel me-1"/>Filters</button>{selected>0&&<button className="btn btn-dark btn-sm" onClick={onBulk}>{selected} selected · Actions</button>}<button className="btn btn-outline-secondary btn-sm" onClick={()=>{const blob=new Blob([issuance.map(r=>r.join(",")).join("\n")]); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="card-issuance.csv"; a.click();}}>Export CSV</button></div></div>; }
function Controls({ onEdit }: { onEdit:(x:string)=>void }) { return <section><div className="pm-card"><Table headers={["Control","Physical","Virtual","Corporate","Prepaid","Premium metal","Action"]} rows={controls} render={(r)=><>{r.map((x,i)=><td key={i} className={i>0?"pm-num":"pm-td-strong"}>{x}</td>)}<td><button className="btn btn-sm btn-outline-primary" onClick={()=>onEdit(r[0])}>Edit</button></td></>}/></div><div className="pm-section-head"><div><h3>Control guardrails</h3><p>Changes are evaluated against risk policy and require two approvers.</p></div></div><div className="row g-3"><div className="col-md-4"><Insight icon="bi-shield-check" title="Auto-lock" value="Enabled" body="All programs · real-time fraud response"/></div><div className="col-md-4"><Insight icon="bi-globe2" title="International spend" value="4 / 5 programs" body="Prepaid remains domestic-only"/></div><div className="col-md-4"><Insight icon="bi-hand-index" title="Contactless" value="3 / 5 programs" body="Virtual and prepaid disabled"/></div></div></section>; }
function PinTab({ onAction }:{onAction:(a:string,b:React.ReactNode)=>void}) { return <section><div className="row g-3 mb-3">{[["Cards with PIN set","94,310","100% of active"],["PIN changes (30d)","1,234","2.3 sec average"],["PIN locked","89","23 admin resets"]].map(x=><div className="col-md-4" key={x[0]}><div className="pm-stat"><div className="pm-stat-label">{x[0]}</div><div className="pm-stat-value">{x[1]}</div><div className="pm-stat-foot">{x[2]}</div></div></div>)}</div><div className="pm-card"><div className="pm-card-head"><div><h5 className="pm-card-title">Replacement & expiry queue</h5><p className="pm-card-sub">Card operations team workload and service levels.</p></div><button className="btn btn-primary btn-sm" onClick={()=>onAction("Create replacement batch", <SettingsForm name="Replacement batch"/>)}>Create batch</button></div><Table headers={["Status","Count","Average processing","Fee","Action"]} rows={[["Expired this month","234","Auto-renewal","KES 0"],["Lost card replacement","45","3 business days","KES 300"],["Damaged replacement","23","3 business days","KES 300"],["Stolen · expedited","12","1 business day","KES 0"],["Upgraded card","56","5 business days","KES 0"]]} render={r=><>{r.map((x,i)=><td key={i} className={i===1?"pm-num":""}>{x}</td>)}<td><button className="btn btn-sm btn-outline-secondary" onClick={()=>onAction("Replacement queue", `Viewing the ${r[0].toLowerCase()} work queue.`)}>View queue</button></td></>}/></div></section>; }
function Financials({onAction}:{onAction:()=>void}) { return <section><div className="pm-card"><Table headers={["Revenue stream","Amount (30d)","Details","Trend"]} rows={[["Interchange revenue","KES 18.5M","1.2% avg interchange","+8.4%"],["Card fees · issuance","KES 2.3M","Physical + corporate","+5.1%"],["FX fees on cards","KES 1.2M","International transactions","+11.7%"],["Total card revenue","KES 22.0M","","+8.1%"],["Card program costs","KES 8.2M","Issuance + network + ops","+3.2%"],["Net card margin","KES 13.8M","62.7% margin","+10.4%"]]} render={r=><>{r.map((x,i)=><td key={i} className={i===1?"pm-num":i===0?"pm-td-strong":""}>{i===3||i===5?<b>{x}</b>:x}</td>)}</>}/></div><div className="pm-card pm-card-pad mt-3 d-flex justify-content-between align-items-center flex-wrap gap-2"><div><b>Board-ready card program pack</b><div className="pm-td-sub">Revenue, costs, scheme fees and chargeback recovery · August 2025</div></div><button className="btn btn-outline-primary btn-sm" onClick={onAction}><i className="bi bi-file-earmark-pdf me-1"/>Generate report</button></div></section>; }
function Config({enabled,setEnabled,onSave}:{enabled:Record<string,boolean>;setEnabled:React.Dispatch<React.SetStateAction<Record<string,boolean>>>;onSave:()=>void}) { return <section><div className="pm-card"><div className="pm-card-head"><div><h5 className="pm-card-title">Global card configuration</h5><p className="pm-card-sub">Version 23 · live in production · changes require approval.</p></div><Badge tone="green" dot>Production</Badge></div><div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Setting</th><th>Value</th><th>Scope</th><th>Status</th><th>Action</th></tr></thead><tbody>{config.map(r=><tr key={r[0]}><td className="pm-td-strong">{r[0]}</td><td className="pm-num">{r[1]}</td><td>{r[2]}</td><td><Badge tone="green">{r[3]}</Badge></td><td><button className="btn btn-sm btn-outline-primary" onClick={onSave}>Edit</button></td></tr>)}</tbody></table></div></div><div className="pm-card pm-card-pad mt-3"><h6>Live switches</h6><div className="row g-2">{[["activation","Require activation","New cards must be activated before spend"],["push","Transaction push","Send push notification for every card transaction"],["international","International spend","Allow cross-border authorisations"],["contactless","Contactless","Allow tap-to-pay on eligible cards"]].map(([id,l,b])=><div className="col-md-6" key={id}><label className="pm-switch-row"><span><b>{l}</b><small>{b}</small></span><input type="checkbox" checked={!!enabled[id]} onChange={e=>setEnabled(x=>({...x,[id]:e.target.checked}))}/></label></div>)}</div><div className="d-flex justify-content-end mt-3"><button className="btn btn-primary" onClick={onSave}>Save configuration draft</button></div></div></section>; }
function SettingsForm({name}:{name:string}) { return <div className="row g-3"><div className="col-md-7"><label className="form-label">Program name</label><input className="form-control" defaultValue={name === "New program" ? "PayMo Everyday" : name}/></div><div className="col-md-5"><label className="form-label">Card type</label><select className="form-select"><option>Physical</option><option>Virtual</option><option>Corporate</option><option>Prepaid</option></select></div><div className="col-md-6"><label className="form-label">Monthly spend limit</label><input className="form-control" defaultValue="500000" /></div><div className="col-md-6"><label className="form-label">Daily spend limit</label><input className="form-control" defaultValue="100000" /></div><div className="col-12"><label className="form-label">Approval note</label><textarea className="form-control" rows={3} defaultValue="Requested by Card Operations for the August product cycle." /></div></div>; }
function Insight({icon,title,value,body}:{icon:string;title:string;value:string;body:string}) { return <div className="pm-card pm-card-pad"><div className="d-flex gap-2"><div className="pm-stat-ico bg-green-soft text-green"><i className={`bi ${icon}`}/></div><div><div className="pm-stat-label">{title}</div><div className="h5 mb-1">{value}</div><div className="pm-td-sub">{body}</div></div></div></div>; }
