import { useState } from "react";
import { Badge, Drawer, Modal, Steps, useToast } from "../../../components/ui";
import { AuthorityPanel } from "../../../components/AuthorityPanel";
import { kes } from "../../../lib/format";
import type { BlacklistEntry, FraudAlert, FraudRule } from "../data/fraudData";

export function AlertDrawer({ alert, onClose, onAssign, onBlock, onResolve }: { alert: FraudAlert | null; onClose: () => void; onAssign: (a: FraudAlert) => void; onBlock: (a: FraudAlert) => void; onResolve: (a: FraudAlert) => void }) {
  const { push } = useToast();
  return <Drawer open={!!alert} onClose={onClose} title={alert ? `${alert.id} · ${alert.type}` : "Alert"} subtitle="Live evidence and decision record" icon="bi-shield-exclamation" tone="red" wide footer={alert && <><button className="btn btn-outline-secondary btn-sm" onClick={() => onAssign(alert)}><i className="bi bi-person-plus me-1" />Assign</button><button className="btn btn-outline-danger btn-sm" onClick={() => onBlock(alert)}><i className="bi bi-slash-circle me-1" />Block activity</button><button className="btn btn-primary btn-sm" onClick={() => onResolve(alert)}><i className="bi bi-check2-circle me-1" />Resolve alert</button></>}>
    {alert && <div className="fraud-detail">
      <div className="d-flex justify-content-between align-items-center mb-3 gap-2"><AuthorityPanel area="Fraud response" auditRef="AUD-FRD-88232" permissions={["Place and release transaction holds", "Freeze or blacklist customers", "Reassign investigations", "Export redacted evidence"]}/><Badge tone="ink"><i className="bi bi-journal-check"/>Audit retained</Badge></div>
      <div className="fraud-score"><div><span>RISK SCORE</span><strong>{alert.risk}</strong><small>/ 100</small></div><Badge tone={alert.risk >= 80 ? "red" : "amber"}>{alert.risk >= 80 ? "Critical review" : "Elevated review"}</Badge></div>
      <div className="fraud-detail-grid"><Info l="Customer" v={alert.user} s={alert.userId} /><Info l="Value at risk" v={kes(alert.amount)} s={alert.channel} /><Info l="Device" v={alert.device} s={alert.ip} /><Info l="Account age" v={`${alert.ageDays} days`} s={`KYC: ${alert.kyc}`} /></div>
      <h6>Why this fired</h6><div className="d-flex flex-wrap gap-2 mb-4">{alert.factors.map(x => <Badge key={x} tone="amber"><i className="bi bi-exclamation-circle" />{x}</Badge>)}</div>
      <h6>Decision trail</h6><div className="fraud-timeline"><p><b>{alert.time}</b><span>Rule engine created the alert from {alert.type.toLowerCase()}.</span></p><p><b>14:33</b><span>Transaction hold is active for 30 minutes while reviewed.</span></p><p><b>Now</b><span>Awaiting investigator action · SLA {alert.slaH ? `${alert.slaH}h remaining` : "completed"}.</span></p></div>
      <div className="fraud-workspace"><div className="fraud-workspace-head"><div><h6>Investigation workspace</h6><small>Evidence is sealed when a case action is taken.</small></div><Badge tone="violet">Case-ready</Badge></div><div className="fraud-workspace-grid"><button onClick={()=>push({kind:"info",title:"User activity loaded",body:"24-hour login, transaction and profile timeline is available in the retained case record."})}><i className="bi bi-clock-history"/><span><b>User timeline</b><small>24h activity trail</small></span></button><button onClick={()=>push({kind:"info",title:"Device evidence opened",body:`Fingerprint ${alert.device} and ${alert.ip} are attached to this case.`})}><i className="bi bi-pc-display"/><span><b>Device fingerprint</b><small>IP, browser, geo & hash</small></span></button><button onClick={()=>push({kind:"info",title:"Linked-account graph prepared",body:"Shared IP, device and payment relationships were correlated."})}><i className="bi bi-diagram-3"/><span><b>Related accounts</b><small>4 network connections</small></span></button><button onClick={()=>push({kind:"info",title:"Evidence locker opened",body:"Login logs, transaction records and API events are sealed for export."})}><i className="bi bi-safe2"/><span><b>Evidence locker</b><small>9 retained artifacts</small></span></button></div><div className="d-flex gap-2 flex-wrap mt-3"><button className="btn btn-outline-secondary btn-sm" onClick={()=>push({kind:"info",title:"Customer contact task created",body:`Secure contact task attached to ${alert.id}.`})}><i className="bi bi-telephone-outbound me-1"/>Contact customer</button><button className="btn btn-outline-secondary btn-sm" onClick={()=>push({kind:"warning",title:"Law-enforcement escalation drafted",body:`Referral draft linked to ${alert.id}; Super Admin review required.`})}><i className="bi bi-bank me-1"/>Escalate</button><button className="btn btn-outline-secondary btn-sm" onClick={()=>push({kind:"info",title:"SAR draft created",body:`A protected SAR workspace was created from ${alert.id}.`})}><i className="bi bi-file-earmark-text me-1"/>Draft SAR</button></div></div>
    </div>}
  </Drawer>;
}
function Info({ l, v, s }: {l:string;v:string;s:string}) { return <div><span>{l}</span><b>{v}</b><small>{s}</small></div>; }

export function AssignModal({ alert, onClose, onSubmit }: { alert: FraudAlert | null; onClose: () => void; onSubmit: (name: string) => void }) {
  const [name, setName] = useState("Sarah K.");
  return <Modal open={!!alert} onClose={onClose} title="Assign investigation" subtitle={alert ? `${alert.id} · ${alert.user}` : ""} icon="bi-person-plus" tone="blue" footer={<><button className="btn btn-outline-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary" onClick={() => onSubmit(name)}>Assign case</button></>}><div className="p-4"><label className="form-label">Investigator</label><select className="form-select" value={name} onChange={e=>setName(e.target.value)}><option>Sarah K.</option><option>James O.</option><option>David K.</option><option>Grace M.</option></select><div className="alert alert-info mt-3 mb-0 small"><i className="bi bi-info-circle me-1" />Assignment creates an immutable audit event and starts the 4-hour review SLA.</div></div></Modal>;
}

export function BlockModal({ alert, onClose, onConfirm }: { alert: FraudAlert | null; onClose: () => void; onConfirm: () => void }) {
  return <Modal open={!!alert} onClose={onClose} title="Block suspicious activity" subtitle="A privileged action with immediate customer impact" icon="bi-slash-octagon" tone="red" footer={<><button className="btn btn-outline-secondary" onClick={onClose}>Keep monitoring</button><button className="btn btn-danger" onClick={onConfirm}>Block & log action</button></>}><div className="p-4"><div className="alert alert-danger small"><b>What happens next:</b> outgoing transfers and withdrawals are stopped for this customer. Existing authorisations remain preserved as evidence.</div><label className="form-label">Reason for block</label><textarea className="form-control" defaultValue={`Fraud control applied for ${alert?.id}; investigator review required before release.`} rows={3}/><div className="form-check mt-3"><input className="form-check-input" id="notify" type="checkbox" defaultChecked/><label className="form-check-label" htmlFor="notify">Notify the fraud response channel</label></div></div></Modal>;
}

export function RuleModal({ rule, onClose, onSave }: { rule: FraudRule | null; onClose: () => void; onSave: (active: boolean) => void }) {
 const [active, setActive] = useState(rule?.active ?? true);
 return <Modal open={!!rule} onClose={onClose} title="Rule control" subtitle={rule ? `${rule.id} · last tuned ${rule.lastTuned}` : ""} icon="bi-sliders" tone="violet" footer={<><button className="btn btn-outline-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary" onClick={()=>onSave(active)}>Save control</button></>}><div className="p-4"><div className="mb-3"><AuthorityPanel area="Fraud rule production control" auditRef="AUD-RULE-75102" permissions={["Tune thresholds", "Pause production rules", "Set enforcement severity", "Approve rule overrides"]}/></div>{rule && <><div className="fraud-rule-box"><b>{rule.name}</b><p>{rule.trigger}</p></div><div className="row g-3 mt-1"><div className="col-6"><label className="form-label">Severity</label><select className="form-select" defaultValue={rule.severity}><option>Critical</option><option>High</option><option>Medium</option></select></div><div className="col-6"><label className="form-label">False positive rate</label><input className="form-control" defaultValue={`${rule.fpRate}%`} /></div></div><div className="form-check form-switch mt-4"><input className="form-check-input" type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)} id="activeRule"/><label className="form-check-label" htmlFor="activeRule">Rule is active in production</label></div></>}</div></Modal>;
}

export function BlacklistModal({ onClose, onAdd }: { onClose: () => void; onAdd: (v:string) => void }) {
 const [step,setStep]=useState(0); const [value,setValue]=useState("");
 return <Modal open={true} onClose={onClose} title="Add blacklist entry" subtitle="Manual entries require a reason and remain fully auditable" icon="bi-slash-circle" tone="red" footer={<>{step>0&&<button className="btn btn-outline-secondary" onClick={()=>setStep(step-1)}>Back</button>}<button className="btn btn-primary" onClick={()=> step<2 ? setStep(step+1) : onAdd(value)}>{step===2?"Confirm entry":"Continue"}</button></>}><div className="p-4"><div className="mb-3"><AuthorityPanel area="Blacklist management" auditRef="AUD-BL-42019" permissions={["Add and remove identifiers", "Block device, IP and payment instruments", "Override automated block decisions", "Export watchlist evidence"]}/></div><Steps current={step} steps={[{label:"Entity",icon:"bi-fingerprint"},{label:"Evidence",icon:"bi-paperclip"},{label:"Confirm",icon:"bi-check2-circle"}]}/>{step===0&&<div className="mt-4"><label className="form-label">Entity type</label><select className="form-select mb-3"><option>Device fingerprint</option><option>IP address</option><option>Phone number</option><option>National ID</option></select><label className="form-label">Value</label><input className="form-control" value={value} onChange={e=>setValue(e.target.value)} placeholder="Enter the identifier" /></div>}{step===1&&<div className="mt-4"><label className="form-label">Evidence and reason</label><textarea className="form-control" rows={4} defaultValue="Linked to fraud investigation and reviewed by Fraud Operations."/><div className="alert alert-warning small mt-3 mb-0">Attach evidence in the case record after saving this entry.</div></div>}{step===2&&<div className="mt-4 alert alert-danger"><b>Final confirmation</b><br/>This entity will be blocked across PayMo channels immediately. A record will be sent to the audit log.</div>}</div></Modal>;
}

export function EntryDrawer({ entry, onClose, onRemove }: {entry:BlacklistEntry|null;onClose:()=>void;onRemove:(e:BlacklistEntry)=>void}) { return <Drawer open={!!entry} onClose={onClose} title="Blacklist entry" subtitle={entry?.id} icon="bi-fingerprint" tone="red" footer={entry&&<><button className="btn btn-outline-secondary btn-sm" onClick={onClose}>Close</button><button className="btn btn-outline-danger btn-sm" onClick={()=>onRemove(entry)}>Remove entry</button></>} >{entry&&<div className="fraud-detail"><div className="fraud-detail-grid"><Info l="Entity" v={entry.value} s={entry.type}/><Info l="Detection hits" v={String(entry.hits)} s="Since block"/><Info l="Added" v={entry.added} s={entry.addedBy}/><Info l="Reason" v={entry.reason} s="Case-linked"/></div><div className="alert alert-info small">Removal restores eligibility but does not erase the retained investigation evidence.</div></div>}</Drawer> }
