import { useEffect, useMemo, useState } from "react";
import { Avatar, Badge, DDItem, Donut, Dropdown, Meter, Pagination, useToast } from "../../../components/ui";
import { csvDownload, kes } from "../../../lib/format";
import { AuthorityPanel } from "../../../components/AuthorityPanel";
import { ALERTS, AMOUNT_HEAT, BLACKLIST_ENTRIES, BLACKLIST_TYPES, CHANNEL_HEAT, COUNTY_HEAT, DEVICE_HEAT, FRAUD_KPI, FRAUD_RULES, HEAT_DAYS, HEATMAP, LOSSES, PATTERNS, SARS, TEAM, type BlacklistEntry, type FraudAlert, type FraudRule } from "../data/fraudData";
import { AlertDrawer, AssignModal, BlacklistModal, BlockModal, EntryDrawer, RuleModal } from "../modals/FraudModals";
import "../styles/fraud.css";

export function FraudDashboard({ signal, onNavigate }: { signal: { action: string; n: number }; onNavigate: (id: string) => void }) {
 const { push } = useToast();
 const [alerts,setAlerts]=useState<FraudAlert[]>(ALERTS); const [tab,setTab]=useState("All"); const [query,setQuery]=useState(""); const [page,setPage]=useState(1);
 const [focus,setFocus]=useState<FraudAlert|null>(null); const [assign,setAssign]=useState<FraudAlert|null>(null); const [block,setBlock]=useState<FraudAlert|null>(null); const [rule,setRule]=useState<FraudRule|null>(null); const [rules,setRules]=useState(FRAUD_RULES); const [blacklist,setBlacklist]=useState(BLACKLIST_ENTRIES); const [newBlock,setNewBlock]=useState(false); const [entry,setEntry]=useState<BlacklistEntry|null>(null);
 useEffect(()=>{ if(signal.n && signal.action==="fraud") setFocus(alerts[0]); },[signal]);
 const filtered=useMemo(()=>alerts.filter(a=>(tab==="All"||a.status===tab) && `${a.id} ${a.user} ${a.type}`.toLowerCase().includes(query.toLowerCase())),[alerts,tab,query]);
 const rows=filtered.slice((page-1)*6,page*6); const unassigned=alerts.filter(x=>x.assigned==="Unassigned"&&x.status!=="Resolved").length;
 const update=(id:string, patch:Partial<FraudAlert>)=>setAlerts(a=>a.map(x=>x.id===id?{...x,...patch}:x));
 const doAssign=(name:string)=>{if(assign){update(assign.id,{assigned:name,status:"In review"}); setAssign(null); setFocus(null); push({kind:"success",title:"Investigation assigned",body:`${assign.id} is now owned by ${name}.`});}};
 const doBlock=()=>{if(block){update(block.id,{status:"Escalated"});setBlock(null);setFocus(null);push({kind:"warning",title:"Activity blocked",body:`Controls applied for ${block.user}; action logged.`});}};
 const lossTotal=LOSSES.reduce((s,x)=>s+x.amount,0), recovery=LOSSES.reduce((s,x)=>s+x.recovery,0);
 return <>
  <div className="pm-section-head fraud-top" style={{marginTop:0}}><div><div className="d-flex gap-2 align-items-center mb-1"><span className="pm-eyebrow">Fraud & risk · Page 15</span><span className="pm-live"><span className="pm-dot red pm-pulse"/>Real-time decisioning</span></div><h2>Fraud command center</h2><p>Protect customers and PayMo funds with live alert triage, loss recovery, rule controls and an auditable blacklist.</p></div><div className="d-flex gap-2 flex-wrap"><AuthorityPanel area="Fraud command center" auditRef="AUD-FRD-00015" permissions={["Block and release transactions", "Freeze accounts and cards", "Manage blacklist and fraud rules", "Export protected case data"]}/><button className="btn btn-outline-secondary btn-sm" onClick={()=>csvDownload("paymo-fraud-alerts.csv",alerts)}><i className="bi bi-download me-1"/>Export queue</button><button className="btn btn-outline-secondary btn-sm" onClick={()=>onNavigate("sar")}><i className="bi bi-file-earmark-text me-1"/>SAR monitoring</button><Dropdown width={245} trigger={()=> <button className="btn btn-outline-secondary btn-sm"><i className="bi bi-three-dots"/></button>}>{close=><><div className="pm-dd-head">Fraud operations</div><DDItem icon="bi-diagram-3" label="Risk scoring engine" hint="Model health & overrides" onClick={()=>{close();onNavigate("risk-scoring")}}/><DDItem icon="bi-shield-check" label="AML & sanctions" hint="Screening and watchlists" onClick={()=>{close();onNavigate("aml")}}/><DDItem icon="bi-life-preserver" label="Incident response" hint="Containment playbooks" onClick={()=>{close();onNavigate("incident")}}/></>}</Dropdown><button className="btn btn-primary btn-sm" onClick={()=>setNewBlock(true)}><i className="bi bi-plus-lg me-1"/>Blacklist entity</button></div></div>
  <div className="row g-2 mb-3">{FRAUD_KPI({newAlerts:alerts.filter(a=>a.status==="New").length,unassigned}).map(s=><div className="col-6 col-md-3 col-xxl-3" key={s.label}><div className="pm-stat"><div className="d-flex gap-2 align-items-center"><span className="pm-stat-ico" style={{background:s.tone==="red"?"#fef2f2":s.tone==="amber"?"#fff5e6":s.tone==="green"?"#e7f8ef":"#f4f1ff",color:s.tone==="red"?"#d92d20":s.tone==="amber"?"#b54708":s.tone==="green"?"#0b8f52":"#5925dc"}}><i className={`bi ${s.icon}`}/></span><span className="pm-stat-label">{s.label}</span></div><div className="pm-stat-value">{s.value}</div><div className="pm-stat-foot">{s.note}</div></div></div>)}</div>
  <div className="row g-3"><div className="col-xl-8"><section className="pm-card h-100"><div className="pm-card-head"><div><h3 className="pm-card-title">Active alert queue <Badge tone="red" className="ms-1">{filtered.filter(a=>a.status!=="Resolved").length} live</Badge></h3><p className="pm-card-sub">Critical decisions and evidence remain in one reviewable queue.</p></div><div className="fraud-search"><i className="bi bi-search"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search ID, person or signal"/></div></div><div className="pm-tabs">{["All","New","In review","Escalated","Resolved"].map(t=><button key={t} className={`pm-tab ${tab===t?"active":""}`} onClick={()=>{setTab(t);setPage(1)}}>{t}{t!=="All"&&<span className="cnt">{alerts.filter(a=>a.status===t).length}</span>}</button>)}</div><div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Alert & customer</th><th>Signal</th><th>Value at risk</th><th>Risk</th><th>Owner / SLA</th><th>Status</th><th/></tr></thead><tbody>{rows.map(a=><tr key={a.id} onClick={()=>setFocus(a)}><td><b className="pm-td-strong">{a.id}</b><div className="pm-td-sub">{a.user} · {a.userId}</div></td><td><b>{a.type}</b><div className="pm-td-sub">{a.time} · {a.channel}</div></td><td className="pm-num">{kes(a.amount)}</td><td><span className={`fraud-risk ${a.risk>=80?"critical":a.risk>=70?"high":"medium"}`}>{a.risk}</span></td><td><b>{a.assigned}</b><div className="pm-td-sub">{a.slaH?`${a.slaH}h SLA remaining`:"Decision recorded"}</div></td><td><Badge tone={a.status==="New"?"red":a.status==="In review"?"amber":a.status==="Escalated"?"violet":"green"}>{a.status}</Badge></td><td onClick={e=>e.stopPropagation()}><Dropdown width={190} trigger={()=><button className="btn btn-light btn-sm"><i className="bi bi-three-dots-vertical"/></button>}>{close=><><DDItem icon="bi-eye" label="Review evidence" onClick={()=>{close();setFocus(a)}}/><DDItem icon="bi-person-plus" label="Assign case" onClick={()=>{close();setAssign(a)}}/><DDItem icon="bi-slash-circle" label="Block activity" danger onClick={()=>{close();setBlock(a)}}/></>}</Dropdown></td></tr>)}</tbody></table></div><Pagination page={page} total={filtered.length} pageSize={6} onPage={setPage}/></section></div>
  <div className="col-xl-4"><section className="pm-card h-100"><div className="pm-card-head"><div><h3 className="pm-card-title">Loss & recovery</h3><p className="pm-card-sub">Confirmed fraud · trailing 30 days</p></div><Badge tone="green">67% recovered</Badge></div><div className="fraud-loss"><Donut size={148} thickness={22} data={[{label:"Recovered",value:recovery,color:"#12b76a"},{label:"Net loss",value:lossTotal-recovery,color:"#f04438"}]} center={<div className="text-center"><b className="d-block" style={{fontSize:".9rem"}}>{kes(lossTotal,{compact:true})}</b><small>gross loss</small></div>}/><div>{LOSSES.map(x=><div className="fraud-loss-row" key={x.category}><span className="fraud-loss-dot" style={{background:x.trend==="up"?"#f04438":x.trend==="down"?"#12b76a":"#f79009"}}/><div className="flex-grow-1"><b>{x.category}</b><small>Recovery {kes(x.recovery,{compact:true})}</small></div><strong>{kes(x.amount-x.recovery,{compact:true})}</strong></div>)}</div></div><div className="fraud-callout"><i className="bi bi-lightning-charge-fill"/><div><b>Priority recovery opportunity</b><span>Account takeover cases represent 37% of gross fraud. Two holds expire within 41 minutes.</span></div><button className="btn btn-sm btn-outline-primary" onClick={()=>setFocus(alerts.find(a=>a.type.includes("takeover"))??alerts[0])}>Review</button></div></section></div></div>
  <div className="row g-3 mt-0"><div className="col-xl-7"><section className="pm-card"><div className="pm-card-head"><div><h3 className="pm-card-title">Fraud rule controls</h3><p className="pm-card-sub">Production rules, calibration quality and live hit count.</p></div><button className="btn btn-outline-secondary btn-sm" onClick={()=>setRule(rules[0])}>Manage rules</button></div><div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Rule</th><th>Severity</th><th>30d hits</th><th>False positives</th><th>State</th><th/></tr></thead><tbody>{rules.slice(0,7).map(r=><tr key={r.id} onClick={()=>setRule(r)}><td><b>{r.id} · {r.name}</b><div className="pm-td-sub">{r.trigger}</div></td><td><Badge tone={r.severity==="Critical"?"red":r.severity==="High"?"amber":"blue"}>{r.severity}</Badge></td><td className="pm-num">{r.hits30d}</td><td><Meter value={r.fpRate} tone={r.fpRate>40?"#f79009":"#12b76a"}/><small className="ms-2">{r.fpRate}%</small></td><td><Badge tone={r.active?"green":"grey"}>{r.active?"Active":"Paused"}</Badge></td><td><i className="bi bi-chevron-right text-muted"/></td></tr>)}</tbody></table></div></section></div><div className="col-xl-5"><section className="pm-card h-100"><div className="pm-card-head"><div><h3 className="pm-card-title">Pattern intelligence</h3><p className="pm-card-sub">Signals clustered by the detection engine.</p></div><button className="btn btn-outline-secondary btn-sm" onClick={()=>onNavigate("risk-scoring")}>Model view</button></div><div className="fraud-patterns">{PATTERNS.slice(0,5).map(p=><div key={p.id}><span className="fraud-pattern-icon"><i className="bi bi-bezier2"/></span><div className="flex-grow-1"><b>{p.name}</b><small>{p.description}</small></div><div className="text-end"><strong>{p.freq30d}</strong><small>30d detections</small></div></div>)}</div></section></div></div>
  <div className="row g-3 mt-0"><div className="col-xl-7"><section className="pm-card"><div className="pm-card-head"><div><h3 className="pm-card-title">Blacklist intelligence</h3><p className="pm-card-sub">Automated and investigator-managed blocks across every channel.</p></div><button className="btn btn-primary btn-sm" onClick={()=>setNewBlock(true)}><i className="bi bi-plus-lg me-1"/>Add entity</button></div><div className="fraud-blacklist-types">{BLACKLIST_TYPES.map(t=><button key={t.id} onClick={()=>setEntry(blacklist.find(e=>e.type===t.type)??blacklist[0])}><i className={`bi ${t.icon}`}/><span><b>{t.entries.toLocaleString()}</b><small>{t.type}</small></span><em>+{t.added30d}</em></button>)}</div><div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Entity</th><th>Reason</th><th>Added by</th><th>Hits</th><th/></tr></thead><tbody>{blacklist.slice(0,5).map(e=><tr key={e.id} onClick={()=>setEntry(e)}><td><b>{e.value}</b><div className="pm-td-sub">{e.type} · {e.id}</div></td><td>{e.reason}</td><td>{e.addedBy}<div className="pm-td-sub">{e.added}</div></td><td><Badge tone="red">{e.hits} blocked</Badge></td><td><i className="bi bi-chevron-right text-muted"/></td></tr>)}</tbody></table></div></section></div><div className="col-xl-5"><section className="pm-card h-100"><div className="pm-card-head"><div><h3 className="pm-card-title">Investigator capacity</h3><p className="pm-card-sub">Workload balanced against quality and SLA.</p></div><Badge tone="amber">1 over 80%</Badge></div><div className="fraud-team">{TEAM.map(t=><div key={t.id}><Avatar name={t.name}/><div className="flex-grow-1"><b>{t.name}</b><small>{t.resolved}/{t.assigned} resolved · {t.accuracy}% accuracy</small><Meter value={t.load} tone={t.load>80?"#f79009":"#12b76a"} width={150}/></div><div className="text-end"><strong>{t.load}%</strong><small>{t.avgTime}</small></div></div>)}</div></section></div></div>
  <div className="row g-3 mt-0"><div className="col-xl-7"><section className="pm-card"><div className="pm-card-head"><div><h3 className="pm-card-title">Attempt heatmap</h3><p className="pm-card-sub">Relative alert intensity by hour and day. Darker cells demand staffing attention.</p></div><Badge tone="amber">Peak: 20:00–23:00</Badge></div><div className="fraud-heat-wrap"><div className="fraud-heat-hours">{Array.from({length:24},(_,i)=><span key={i}>{i%3===0?String(i).padStart(2,"0"):""}</span>)}</div>{HEATMAP.map((d,i)=><div className="fraud-heat-row" key={HEAT_DAYS[i]}><b>{HEAT_DAYS[i]}</b>{d.map((v,j)=><i key={j} style={{opacity:.15+v*.17}} title={`${HEAT_DAYS[i]} ${j}:00 · intensity ${v}`}/>)}</div>)}</div></section></div><div className="col-xl-5"><section className="pm-card h-100"><div className="pm-card-head"><div><h3 className="pm-card-title">Attack surface mix</h3><p className="pm-card-sub">30-day distribution by channel and device.</p></div></div><div className="fraud-mix">{CHANNEL_HEAT.map(x=><div key={x.n}><span>{x.n}</span><Meter value={x.v} tone={x.c} width={190}/><b>{x.v}%</b></div>)}</div><div className="fraud-mini-pills">{DEVICE_HEAT.map(x=><span key={x.n}>{x.n}<b>{x.v}%</b></span>)}</div></section></div></div>
  <section className="pm-card mt-3"><div className="pm-card-head"><div><h3 className="pm-card-title">Regulatory filings & law-enforcement referrals</h3><p className="pm-card-sub">FRA submission status, authority receipts and retained case references.</p></div><button className="btn btn-outline-secondary btn-sm" onClick={()=>onNavigate("sar")}><i className="bi bi-arrow-right me-1"/>Open SAR pipeline</button></div><div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>SAR reference</th><th>Subject</th><th>Reported amount</th><th>Activity type</th><th>Authority receipt</th><th>Status</th></tr></thead><tbody>{SARS.map(s=><tr key={s.id} onClick={()=>onNavigate("sar")}><td><b>{s.id}</b><div className="pm-td-sub">Filed {s.filedDate}</div></td><td>{s.userId}</td><td className="pm-num">{kes(s.amount)}</td><td>{s.type}</td><td className="mono">{s.receipt}</td><td><Badge tone={s.status==="Acknowledged"?"green":"amber"}>{s.status}</Badge></td></tr>)}</tbody></table></div></section>
  <AlertDrawer alert={focus} onClose={()=>setFocus(null)} onAssign={a=>{setFocus(null);setAssign(a)}} onBlock={a=>{setFocus(null);setBlock(a)}} onResolve={a=>{update(a.id,{status:"Resolved"});setFocus(null);push({kind:"success",title:"Alert resolved",body:`${a.id} has been closed with an audit record.`})}}/>
  <AssignModal alert={assign} onClose={()=>setAssign(null)} onSubmit={doAssign}/>
  <BlockModal alert={block} onClose={()=>setBlock(null)} onConfirm={doBlock}/>
  <RuleModal rule={rule} onClose={()=>setRule(null)} onSave={(active) => {
    if (!rule) return;
    setRules((rs) => rs.map((r) => r.id === rule.id ? { ...r, active } : r));
    push({ kind:"success", title:"Rule control saved", body:`${rule.id} is ${active ? "active" : "paused"} in production.` });
    setRule(null);
  }}/>
  {newBlock && <BlacklistModal onClose={()=>setNewBlock(false)} onAdd={(value)=>{
    const e:BlacklistEntry={id:`BLE-${String(502+blacklist.length).padStart(4,"0")}`,type:"Device fingerprints",value:value||"New manual entity",reason:"Investigator-managed block",added:"Just now",addedBy:"Joseph Mwangi",hits:0};
    setBlacklist(x=>[e,...x]); setNewBlock(false);
    push({kind:"success",title:"Blacklist entry created",body:"The entity is now blocked across applicable channels."});
  }}/>} 
  <EntryDrawer entry={entry} onClose={()=>setEntry(null)} onRemove={(e)=>{
    setBlacklist(x=>x.filter(a=>a.id!==e.id)); setEntry(null);
    push({kind:"warning",title:"Blacklist entry removed",body:`${e.id} was removed and retained in the audit trail.`});
  }}/>
 </>;
}
